export const mockData = [
	{
		id: 12038971381,
		title: 'X',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'John',
		date_created: 321989999,
		image: '/images/top.png',
		favorites: false,
	},
	{
		id: 28017381738,
		title: 'D',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Destroyer',
		date_created: 321989999,
		image: '/images/top.png',
		favorites: true,
	},
	{
		id: 12983138137,
		title: 'O',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Sarge',
		date_created: 321989999,
		image: '/images/top.png',
		favorites: false,
	},
	{
		id: 31298737813,
		title: 'J',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'John',
		date_created: 321989999,
		image: '/images/base.png',
		favorites: false,
	},
	{
		id: 12978631897,
		title: 'A',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Destroyer',
		date_created: 321989999,
		image: '/images/base.png',
		favorites: true,
	},
	{
		id: 69785985492,
		title: 'Z',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Sarge',
		date_created: 321989999,
		image: '/images/base.png',
		favorites: false,
	},
	{
		id: 30894569853,
		title: 'Q',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'John',
		date_created: 321989999,
		image: '/images/aphrodite.png',
		favorites: true,
	},
	{
		id: 68347587599,
		title: 'R',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Destroyer',
		date_created: 321989999,
		image: '/images/aphrodite.png',
		favorites: true,
	},
	{
		id: 38274827490,
		title: 'G',
		description: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy Lorem Ipsum is simply dummy text of the printing and typese`,
		author: 'Sarge',
		date_created: 321989999,
		image: '/images/aphrodite.png',
		favorites: false,
	},
];
