import '@/styles/globals.css';
import '../utils/axiosConfig';

import Head from 'next/head';
import type {AppProps} from 'next/app';

import {Layout} from '@/components/layout';
import AppProviders from '@/modules/app/AppProviders';

export default function App({Component, pageProps}: AppProps) {
	return (
		<>
			<Head>
				<title>SBC</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AppProviders>
				<Layout>
					<Component {...pageProps} />
				</Layout>
			</AppProviders>
		</>
	);
}
