import '@/styles/globals.css';

import Head from 'next/head';
import type {AppProps} from 'next/app';

import {Page} from '@/components/page';
import AppProviders from '@/modules/app/AppProviders';

export default function App({Component, pageProps}: AppProps) {
	return (
		<>
			<Head>
				<title>SBC</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<AppProviders>
				<Page>
					<Component {...pageProps} />
				</Page>
			</AppProviders>
		</>
	);
}
